services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mongo:27017/sniply
      JWT_SECRET: dev_secret_change_me_in_production
      JWT_EXPIRES: 7d
      CLIENT_URL: http://localhost:5173
      BASE_URL: http://localhost:5000
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5000/api/v1
        VITE_SHORT_BASE: http://localhost:5000
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo-data:
